class AppStringsHelper {
  static Map<String, String> appStrings = {
    'Cancel': '',
    'Are you sure?': '',
    'SafeCart': '',
    'Please select a country': '',
    'Please select a state': '',
    'Profile info successfully updated': '',
    'Profile info updated failed': '',
    'City/Town': '',
    'Enter your city/town': '',
    'Enter a valid city/town': '',
    'Enter a valid address': '',
    'Address added successfully.': '',
    'Failed to add Address.': '',
    'Enter city/town': '',
    'Welcome to': '',
    'Delete': '',
    'Please turn on your internet connection': '',
    'Your payment process will get terminated.': '',
    'Login to checkout?': '',
    'You have to  login to proceed the checkout.': '',
    'Login': '',
    'Logout': '',
    'Submit': '',
    'Compare': '',
    'Home': '',
    'Cart': '',
    'Wishlist': '',
    'profile': '',
    'Search your need here': '',
    'Press again to exit': '',
    'Find Your Style': '',
    'Featured Item': '',
    'Hot Items': '',
    "You'll have to Sign-in/Sign-up to edit or see your profile info.": "",
    'Close': '',
    'Status Change successful': '',
    'Status Change failed': '',
    'Priority Change failed': '',
    'Message sent.': '',
    'Enter a valid card': '',
    'Card': '',
    'Expiry-date': '',
    'Select expiry-date': '',
    'Card code': '',
    'Enter a valid card code': '',
    'No states found': '',
    'Enter a valid coupon': '',
    'Sign up succeeded': '',
    'Invalid email or Password': '',
    'Priority Change successful': '',
    'Sign In': '',
    'Sign out': '',
    'Request timeout': '',
    'OTP send error': '',
    'Password reset successful': '',
    'Password reset failed': '',
    'Something went wrong!': '',
    'Sign in failed': '',
    'Account delete failed': '',
    'Please enter all the shipping info': '',
    'This account has been deleted!': '',
    'Something went wrong': '',
    'Sign up failed': '',
    'Registration succeeded!': '',
    'Select an image from gallery': '',
    'Take an image to proceed': '',
    'Continue': '',
    'Loading failed!': '',
    'Failed to load payment page.': '',
    'Address delete successful.': '',
    'Address delete failed.': '',
    'Return': '',
    'Invalid developer keys': '',
    'Loading failed': '',
    'Connection failed': '',
    'Payment has been failed.': '',
    'Item added to cart': '',
    'Item subtracted from cart': '',
    'Item added to wishlist': '',
    'Item removed from wishlist': '',
    'Add new address': '',
    'Title': '',
    'Enter a title': '',
    'Email': '',
    'Enter an email': '',
    'Phone': '',
    'Enter a phone number': '',
    'Country': '',
    'Select country': '',
    'State': '',
    'Select state': '',
    'City': '',
    'Enter city': '',
    'Zipcode': '',
    'Enter zipcode': '',
    'Address': '',
    'Enter address': '',
    'Add address': '',
    'Categories': '',
    'No item found': '',
    'My Cart': '',
    'Clear cart': '',
    'Add item to cart!': '',
    'Process to checkout': '',
    'These Items will be Deleted.': '',
    'No': '',
    'Yes': '',
    'Change password': '',
    'Enter your current password': '',
    'New password': '',
    'Current password': '',
    'Enter new password': '',
    'Confirm new password': '',
    'Re-enter new password': '',
    'Change Password': '',
    'Write message': '',
    'File': '',
    'Choose file': '',
    'No file chosen': '',
    'Notify via mail': '',
    'Send': '',
    'No Message has been found!': '',
    'Checkout': '',
    'Saved Addresses': '',
    'Products': '',
    'Order summery': '',
    'Subtotal': '',
    'Coupon discount': '',
    'Shipping cost': '',
    'Chose a payment method': '',
    'An error occurred': '',
    'Zito-pay username': '',
    'By creating an account,you agree to the': '',
    'I Have Read And Agree To The Website': '',
    'terms of service and Conditions': '',
    'Terms and Conditions': '',
    'and': '',
    'Privacy Policy': '',
    'privacy policy.': '',
    'Confirm order': '',
    'Name': '',
    'Enter your name': '',
    'Enter your email': '',
    'Enter your phone': '',
    'Enter your city': '',
    'Enter your zipcode': '',
    'Enter your address': '',
    'Save changes': '',
    'Verification Code': '',
    'Enter your verification Code': '',
    "Didn't received?": '',
    'Send again.': '',
    'Wrong OTP Code': '',
    'Resend code': '',
    'Feature Items': '',
    'No more product found': '',
    'Campaigns': '',
    'Reset your password': '',
    'Reset password': '',
    'Please give all the information properly': '',
    "Couldn't add Ticket": '',
    'Add new ticket': '',
    'Enter a valid title': '',
    'Subject': '',
    'Enter a subject': '',
    'Enter a valid subject': '',
    'Enter a subject with more then 5 character': '',
    'Priority': '',
    'Department': '',
    'Description': '',
    'Describe your issue': '',
    'You have to give some description': '',
    'Add Ticket': '',
    'Order': '',
    'Tax': '',
    'Total': '',
    'Order ID': '',
    'Shipping Method': '',
    'Free Shipping': '',
    'Payment Method': '',
    'Payment Status': '',
    'Order Status': '',
    'My orders': '',
    'Failed to load data.': '',
    'No order found.': '',
    'Oops!': '',
    'Payment successful!': '',
    "We're getting problems with your payment methods and we couldn't proceed your order.":
        '',
    "Your order has been successful! You'll receive ordered items in 3-5 days. Your order ID is ":
        '',
    'Back to home': '',
    'Track your order': '',
    'Show more': '',
    'Show less': '',
    'Sub Category': '',
    'Child Category': '',
    'SKU': '',
    'Tags': '',
    "Seller's Products": '',
    'Related Products': '',
    'Shipping address': '',
    'Support Ticket': '',
    'Edit profile': '',
    'Delete account': '',
    'Sign in/Sign up': '',
    'Enter your password': '',
    'Enter a valid email address': '',
    "Send verification code": '',
    "No address found.": '',
    'Add new Address': '',
    "Welcome Back": '',
    "Email/Username": '',
    "Enter your email or username": '',
    "Enter your Password": '',
    "Password must be more then 6 character": '',
    "Remember me": '',
    "Forgot password?": '',
    "Don't have an account?": '',
    "Sign up": '',
    "Sign in with Google": '',
    "Sign in with Facebook": '',
    "You have to select a country": '',
    "You have to select a state": '',
    "You have to agree our terms and conditions": '',
    "Welcome": '',
    "Enter a valid name": '',
    "Username": '',
    "Enter your username": '',
    "Enter a valid username": '',
    "Select your Country": '',
    "Select your State": '',
    "Enter your phone number": '',
    "Password": '',
    "Re-enter your Password": '',
    "Password didn't match": '',
    "Please provide current password": '',
    "Sign Up": '',
    "Already have an account?": '',
    "Sign up with Google": '',
    "Sign up with Facebook": '',
    "My Tickets": '',
    "No ticket found.": '',
    "No data has been found!": '',
    "Items removed from wishlist": '',
    "Clear wishlist": '',
    "Add items to wishlist": '',
    "Attributes": '',
    "None": '',
    "Item removed from cart": '',
    "This Item will be Deleted.": '',
    "'Coupon Text'": '',
    "Apply shipping": '',
    "Shipping information": '',
    "Town/City": '',
    "Enter Town/city name": '',
    "Enter an address": '',
    "Order note": '',
    "Enter Order note": '',
    "select a shipping method": '',
    "Or": '',
    "See All": '',
    "Welcome back": '',
    "Profile": '',
    "Campaign Products": '',
    "Price": '',
    "Quantity": '',
    "Order Summery": '',
    'Order status': '',
    "This order will be canceled.": '',
    "Add to cart": '',
    'Sold count': '',
    "Your rating": '',
    "Your review": '',
    "Write your feedback.": '',
    'From': '',
    "Order Completion Rate": '',
    "About Since": '',
    "Satisfied Client": '',
    "Filter": '',
    "Color": '',
    "Size": '',
    "Brands": '',
    "Filter Price": '',
    "Average Rating": '',
    "Reset Filter": '',
    "Apply Filter": '',
    "This address will be deleted permanently.": '',
    "open": '',
    "close": '',
    "Select attributes": '',
    "Select all attribute to proceed": '',
    "Please select an attribute set": '',
    "Items total": '',
    "You have agree to our Terms & Conditions.": '',
    "SafeCart Products": '',
    "Safecart Products": '',
    "Payment confirm success": '',
    "Payment confirm failed": '',
    "Please enter all the information": '',
    "Sign out successful": '',
    "Password change failed": '',
    "Password change succeeded": '',
    "Review submitted": '',
    "Review submission failed": '',
    "Attribute set selected": '',
    "Order placing failed": '',
    "OTP verification failed!": '',
    "Uploading image, this might take some time...": '',
    "Your order has been successful! You'll receive ordered items in 3-5 days.":
        '',
    "Order submitted!": '',
    "Your order ID  is": '',
    "Ok": '',
    "No more order found": '',
    "No more ticket found": '',
    "No more shipping address found": '',
    "Brand": '',
    "No wifi or cellular data found": '',
    "Invalid url": '',
    "Search State": '',
    "No results found": '',
    "Search country": '',
    "Search city": '',
    "No result found": '',
    "Product stock is insufficient": '',
  };
}
