name: safecart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.5.4

dependency_overrides:
  webview_flutter_android: ^4.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.7
  provider: ^6.0.5
  fluttertoast: ^8.0.4
  sqflite: ^2.2.2
  lottie: ^3.0.0
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  badges: ^3.0.2
  anim_search_bar: ^2.0.3
  chewie: ^1.7.4
  http: ^0.13.5
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  card_swiper: ^3.0.1
  slide_countdown: ^2.0.2
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.1
  expandable_text: ^2.3.0
  file_picker: ^8.1.4
  pinput: ^5.0.0
  timezone_to_country: ^2.2.0
  draggable_home: ^1.0.4
  flutterzilla_fixed_grid: ^0.0.4
  loading_animation_widget: ^1.2.0+4
  flutter_launcher_icons: ^0.13.1
  focused_menu: ^1.0.5
  intl: ^0.19.0
  money_formatter: ^0.0.3
  pluto_menu_bar: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  share_plus: ^10.1.2
  email_validator: ^3.0.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^6.0.4
  flutter_inappwebview: ^6.1.5
  http_auth: ^1.0.1
  flutter_stripe: ^11.3.0
  flutter_widget_from_html: ^0.9.1
  timeago: ^3.3.0
  line_awesome_flutter: ^3.0.1
  photo_view: ^0.15.0
  connectivity_plus: ^6.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
