name: safecart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: '>=3.5.4 <4.0.0'

dependency_overrides:
  webview_flutter_android: ^4.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rflutter_alert: ^2.0.7
  provider: ^6.1.5
  fluttertoast: ^8.2.12
  sqflite: ^2.4.2
  lottie: ^3.3.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  badges: ^3.1.2
  anim_search_bar: ^2.0.3
  chewie: ^1.12.1
  http: ^1.4.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  slide_countdown: ^2.0.2
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.1
  expandable_text: ^2.3.0
  file_picker: ^10.2.0
  pinput: ^5.0.0
  timezone_to_country: ^3.0.0
  draggable_home: ^1.0.4
  flutterzilla_fixed_grid: ^0.0.4
  loading_animation_widget: ^1.2.0+4
  flutter_launcher_icons: ^0.13.1
  focused_menu: ^1.0.5
  pluto_menu_bar: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  share_plus: ^10.1.2
  email_validator: ^3.0.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.2
  flutter_inappwebview: ^6.1.5
  http_auth: ^1.0.4
  flutter_stripe: ^11.5.0
  flutter_widget_from_html: ^0.17.0
  timeago: ^3.7.1
  line_awesome_flutter: ^3.0.1
  photo_view: ^0.15.0
  connectivity_plus: ^6.1.4
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icoon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
